// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/idp (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=internal/idp/client_mock.go -package=idp github.com/osac-project/fulfillment-service/internal/idp Client
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockClient) AddUserToGroup(ctx context.Context, organizationName, idpUserID, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", ctx, organizationName, idpUserID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockClientMockRecorder) AddUserToGroup(ctx, organizationName, idpUserID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockClient)(nil).AddUserToGroup), ctx, organizationName, idpUserID, groupID)
}

// AssignClientRolesToUser mocks base method.
func (m *MockClient) AssignClientRolesToUser(ctx context.Context, organizationName, idpUserID, clientID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignClientRolesToUser", ctx, organizationName, idpUserID, clientID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignClientRolesToUser indicates an expected call of AssignClientRolesToUser.
func (mr *MockClientMockRecorder) AssignClientRolesToUser(ctx, organizationName, idpUserID, clientID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignClientRolesToUser", reflect.TypeOf((*MockClient)(nil).AssignClientRolesToUser), ctx, organizationName, idpUserID, clientID, roles)
}

// AssignIdpManagerPermissions mocks base method.
func (m *MockClient) AssignIdpManagerPermissions(ctx context.Context, idpUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignIdpManagerPermissions", ctx, idpUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignIdpManagerPermissions indicates an expected call of AssignIdpManagerPermissions.
func (mr *MockClientMockRecorder) AssignIdpManagerPermissions(ctx, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignIdpManagerPermissions", reflect.TypeOf((*MockClient)(nil).AssignIdpManagerPermissions), ctx, idpUserID)
}

// AssignOrganizationAdminPermissions mocks base method.
func (m *MockClient) AssignOrganizationAdminPermissions(ctx context.Context, organizationName, idpUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignOrganizationAdminPermissions", ctx, organizationName, idpUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignOrganizationAdminPermissions indicates an expected call of AssignOrganizationAdminPermissions.
func (mr *MockClientMockRecorder) AssignOrganizationAdminPermissions(ctx, organizationName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignOrganizationAdminPermissions", reflect.TypeOf((*MockClient)(nil).AssignOrganizationAdminPermissions), ctx, organizationName, idpUserID)
}

// AssignOrganizationRolesToUser mocks base method.
func (m *MockClient) AssignOrganizationRolesToUser(ctx context.Context, organizationName, idpUserID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignOrganizationRolesToUser", ctx, organizationName, idpUserID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignOrganizationRolesToUser indicates an expected call of AssignOrganizationRolesToUser.
func (mr *MockClientMockRecorder) AssignOrganizationRolesToUser(ctx, organizationName, idpUserID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignOrganizationRolesToUser", reflect.TypeOf((*MockClient)(nil).AssignOrganizationRolesToUser), ctx, organizationName, idpUserID, roles)
}

// CreateAuthorizationGroup mocks base method.
func (m *MockClient) CreateAuthorizationGroup(ctx context.Context, organizationName, groupName, groupPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizationGroup", ctx, organizationName, groupName, groupPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthorizationGroup indicates an expected call of CreateAuthorizationGroup.
func (mr *MockClientMockRecorder) CreateAuthorizationGroup(ctx, organizationName, groupName, groupPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizationGroup", reflect.TypeOf((*MockClient)(nil).CreateAuthorizationGroup), ctx, organizationName, groupName, groupPath)
}

// CreateAuthorizationResource mocks base method.
func (m *MockClient) CreateAuthorizationResource(ctx context.Context, resource *AuthorizationResource) (*AuthorizationResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizationResource", ctx, resource)
	ret0, _ := ret[0].(*AuthorizationResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthorizationResource indicates an expected call of CreateAuthorizationResource.
func (mr *MockClientMockRecorder) CreateAuthorizationResource(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizationResource", reflect.TypeOf((*MockClient)(nil).CreateAuthorizationResource), ctx, resource)
}

// CreateIdentityProvider mocks base method.
func (m *MockClient) CreateIdentityProvider(ctx context.Context, organizationName string, idp *IdentityProvider) (*IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentityProvider", ctx, organizationName, idp)
	ret0, _ := ret[0].(*IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIdentityProvider indicates an expected call of CreateIdentityProvider.
func (mr *MockClientMockRecorder) CreateIdentityProvider(ctx, organizationName, idp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentityProvider", reflect.TypeOf((*MockClient)(nil).CreateIdentityProvider), ctx, organizationName, idp)
}

// CreateOrganization mocks base method.
func (m *MockClient) CreateOrganization(ctx context.Context, org *Organization) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockClientMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockClient)(nil).CreateOrganization), ctx, org)
}

// CreateUser mocks base method.
func (m *MockClient) CreateUser(ctx context.Context, organizationName string, user *User) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, organizationName, user)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockClientMockRecorder) CreateUser(ctx, organizationName, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClient)(nil).CreateUser), ctx, organizationName, user)
}

// DeleteAuthorizationGroup mocks base method.
func (m *MockClient) DeleteAuthorizationGroup(ctx context.Context, organizationName, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthorizationGroup", ctx, organizationName, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthorizationGroup indicates an expected call of DeleteAuthorizationGroup.
func (mr *MockClientMockRecorder) DeleteAuthorizationGroup(ctx, organizationName, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthorizationGroup", reflect.TypeOf((*MockClient)(nil).DeleteAuthorizationGroup), ctx, organizationName, groupID)
}

// DeleteAuthorizationResource mocks base method.
func (m *MockClient) DeleteAuthorizationResource(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthorizationResource", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthorizationResource indicates an expected call of DeleteAuthorizationResource.
func (mr *MockClientMockRecorder) DeleteAuthorizationResource(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthorizationResource", reflect.TypeOf((*MockClient)(nil).DeleteAuthorizationResource), ctx, resourceID)
}

// DeleteIdentityProvider mocks base method.
func (m *MockClient) DeleteIdentityProvider(ctx context.Context, organizationName, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentityProvider", ctx, organizationName, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentityProvider indicates an expected call of DeleteIdentityProvider.
func (mr *MockClientMockRecorder) DeleteIdentityProvider(ctx, organizationName, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentityProvider", reflect.TypeOf((*MockClient)(nil).DeleteIdentityProvider), ctx, organizationName, alias)
}

// DeleteOrganization mocks base method.
func (m *MockClient) DeleteOrganization(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockClientMockRecorder) DeleteOrganization(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockClient)(nil).DeleteOrganization), ctx, name)
}

// DeleteUser mocks base method.
func (m *MockClient) DeleteUser(ctx context.Context, organizationName, idpUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, organizationName, idpUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockClientMockRecorder) DeleteUser(ctx, organizationName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockClient)(nil).DeleteUser), ctx, organizationName, idpUserID)
}

// GetAuthorizationResource mocks base method.
func (m *MockClient) GetAuthorizationResource(ctx context.Context, resourceID string) (*AuthorizationResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationResource", ctx, resourceID)
	ret0, _ := ret[0].(*AuthorizationResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationResource indicates an expected call of GetAuthorizationResource.
func (mr *MockClientMockRecorder) GetAuthorizationResource(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationResource", reflect.TypeOf((*MockClient)(nil).GetAuthorizationResource), ctx, resourceID)
}

// GetGroupIDByPath mocks base method.
func (m *MockClient) GetGroupIDByPath(ctx context.Context, organizationName, groupPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupIDByPath", ctx, organizationName, groupPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupIDByPath indicates an expected call of GetGroupIDByPath.
func (mr *MockClientMockRecorder) GetGroupIDByPath(ctx, organizationName, groupPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupIDByPath", reflect.TypeOf((*MockClient)(nil).GetGroupIDByPath), ctx, organizationName, groupPath)
}

// GetIdentityProvider mocks base method.
func (m *MockClient) GetIdentityProvider(ctx context.Context, organizationName, alias string) (*IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityProvider", ctx, organizationName, alias)
	ret0, _ := ret[0].(*IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityProvider indicates an expected call of GetIdentityProvider.
func (mr *MockClientMockRecorder) GetIdentityProvider(ctx, organizationName, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityProvider", reflect.TypeOf((*MockClient)(nil).GetIdentityProvider), ctx, organizationName, alias)
}

// GetOrganization mocks base method.
func (m *MockClient) GetOrganization(ctx context.Context, name string) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, name)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockClientMockRecorder) GetOrganization(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockClient)(nil).GetOrganization), ctx, name)
}

// GetUser mocks base method.
func (m *MockClient) GetUser(ctx context.Context, organizationName, idpUserID string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, organizationName, idpUserID)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockClientMockRecorder) GetUser(ctx, organizationName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockClient)(nil).GetUser), ctx, organizationName, idpUserID)
}

// GetUserClientRoles mocks base method.
func (m *MockClient) GetUserClientRoles(ctx context.Context, organizationName, idpUserID, clientID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserClientRoles", ctx, organizationName, idpUserID, clientID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserClientRoles indicates an expected call of GetUserClientRoles.
func (mr *MockClientMockRecorder) GetUserClientRoles(ctx, organizationName, idpUserID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserClientRoles", reflect.TypeOf((*MockClient)(nil).GetUserClientRoles), ctx, organizationName, idpUserID, clientID)
}

// GetUserOrganizationRoles mocks base method.
func (m *MockClient) GetUserOrganizationRoles(ctx context.Context, organizationName, idpUserID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrganizationRoles", ctx, organizationName, idpUserID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrganizationRoles indicates an expected call of GetUserOrganizationRoles.
func (mr *MockClientMockRecorder) GetUserOrganizationRoles(ctx, organizationName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrganizationRoles", reflect.TypeOf((*MockClient)(nil).GetUserOrganizationRoles), ctx, organizationName, idpUserID)
}

// ListClientRoles mocks base method.
func (m *MockClient) ListClientRoles(ctx context.Context, organizationName, clientID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientRoles", ctx, organizationName, clientID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientRoles indicates an expected call of ListClientRoles.
func (mr *MockClientMockRecorder) ListClientRoles(ctx, organizationName, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientRoles", reflect.TypeOf((*MockClient)(nil).ListClientRoles), ctx, organizationName, clientID)
}

// ListIdentityProviders mocks base method.
func (m *MockClient) ListIdentityProviders(ctx context.Context, organizationName string) ([]*IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdentityProviders", ctx, organizationName)
	ret0, _ := ret[0].([]*IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdentityProviders indicates an expected call of ListIdentityProviders.
func (mr *MockClientMockRecorder) ListIdentityProviders(ctx, organizationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdentityProviders", reflect.TypeOf((*MockClient)(nil).ListIdentityProviders), ctx, organizationName)
}

// ListOrganizationRoles mocks base method.
func (m *MockClient) ListOrganizationRoles(ctx context.Context, organizationName string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationRoles", ctx, organizationName)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationRoles indicates an expected call of ListOrganizationRoles.
func (mr *MockClientMockRecorder) ListOrganizationRoles(ctx, organizationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationRoles", reflect.TypeOf((*MockClient)(nil).ListOrganizationRoles), ctx, organizationName)
}

// ListUsers mocks base method.
func (m *MockClient) ListUsers(ctx context.Context, organizationName string) ([]*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, organizationName)
	ret0, _ := ret[0].([]*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockClientMockRecorder) ListUsers(ctx, organizationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockClient)(nil).ListUsers), ctx, organizationName)
}

// RemoveClientRolesFromUser mocks base method.
func (m *MockClient) RemoveClientRolesFromUser(ctx context.Context, organizationName, idpUserID, clientID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClientRolesFromUser", ctx, organizationName, idpUserID, clientID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClientRolesFromUser indicates an expected call of RemoveClientRolesFromUser.
func (mr *MockClientMockRecorder) RemoveClientRolesFromUser(ctx, organizationName, idpUserID, clientID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClientRolesFromUser", reflect.TypeOf((*MockClient)(nil).RemoveClientRolesFromUser), ctx, organizationName, idpUserID, clientID, roles)
}

// RemoveOrganizationRolesFromUser mocks base method.
func (m *MockClient) RemoveOrganizationRolesFromUser(ctx context.Context, organizationName, idpUserID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOrganizationRolesFromUser", ctx, organizationName, idpUserID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOrganizationRolesFromUser indicates an expected call of RemoveOrganizationRolesFromUser.
func (mr *MockClientMockRecorder) RemoveOrganizationRolesFromUser(ctx, organizationName, idpUserID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrganizationRolesFromUser", reflect.TypeOf((*MockClient)(nil).RemoveOrganizationRolesFromUser), ctx, organizationName, idpUserID, roles)
}

// RemoveUserFromGroup mocks base method.
func (m *MockClient) RemoveUserFromGroup(ctx context.Context, organizationName, idpUserID, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", ctx, organizationName, idpUserID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockClientMockRecorder) RemoveUserFromGroup(ctx, organizationName, idpUserID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockClient)(nil).RemoveUserFromGroup), ctx, organizationName, idpUserID, groupID)
}

// UpdateOrganization mocks base method.
func (m *MockClient) UpdateOrganization(ctx context.Context, org *Organization) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, org)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockClientMockRecorder) UpdateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockClient)(nil).UpdateOrganization), ctx, org)
}
