// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/public_ips_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/public_ips_service_grpc.pb.go -destination=public_ips_client_mock.go -package=publicip PublicIPsClient
//

// Package publicip is a generated GoMock package.
package publicip

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPublicIPsClient is a mock of PublicIPsClient interface.
type MockPublicIPsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIPsClientMockRecorder
	isgomock struct{}
}

// MockPublicIPsClientMockRecorder is the mock recorder for MockPublicIPsClient.
type MockPublicIPsClientMockRecorder struct {
	mock *MockPublicIPsClient
}

// NewMockPublicIPsClient creates a new mock instance.
func NewMockPublicIPsClient(ctrl *gomock.Controller) *MockPublicIPsClient {
	mock := &MockPublicIPsClient{ctrl: ctrl}
	mock.recorder = &MockPublicIPsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIPsClient) EXPECT() *MockPublicIPsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublicIPsClient) Create(ctx context.Context, in *privatev1.PublicIPsCreateRequest, opts ...grpc.CallOption) (*privatev1.PublicIPsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPublicIPsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublicIPsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockPublicIPsClient) Delete(ctx context.Context, in *privatev1.PublicIPsDeleteRequest, opts ...grpc.CallOption) (*privatev1.PublicIPsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPublicIPsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublicIPsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockPublicIPsClient) Get(ctx context.Context, in *privatev1.PublicIPsGetRequest, opts ...grpc.CallOption) (*privatev1.PublicIPsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublicIPsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublicIPsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockPublicIPsClient) List(ctx context.Context, in *privatev1.PublicIPsListRequest, opts ...grpc.CallOption) (*privatev1.PublicIPsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPublicIPsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPublicIPsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockPublicIPsClient) Signal(ctx context.Context, in *privatev1.PublicIPsSignalRequest, opts ...grpc.CallOption) (*privatev1.PublicIPsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockPublicIPsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockPublicIPsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockPublicIPsClient) Update(ctx context.Context, in *privatev1.PublicIPsUpdateRequest, opts ...grpc.CallOption) (*privatev1.PublicIPsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPublicIPsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublicIPsClient)(nil).Update), varargs...)
}

// MockPublicIPsServer is a mock of PublicIPsServer interface.
type MockPublicIPsServer struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIPsServerMockRecorder
	isgomock struct{}
}

// MockPublicIPsServerMockRecorder is the mock recorder for MockPublicIPsServer.
type MockPublicIPsServerMockRecorder struct {
	mock *MockPublicIPsServer
}

// NewMockPublicIPsServer creates a new mock instance.
func NewMockPublicIPsServer(ctrl *gomock.Controller) *MockPublicIPsServer {
	mock := &MockPublicIPsServer{ctrl: ctrl}
	mock.recorder = &MockPublicIPsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIPsServer) EXPECT() *MockPublicIPsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublicIPsServer) Create(arg0 context.Context, arg1 *privatev1.PublicIPsCreateRequest) (*privatev1.PublicIPsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPublicIPsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublicIPsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPublicIPsServer) Delete(arg0 context.Context, arg1 *privatev1.PublicIPsDeleteRequest) (*privatev1.PublicIPsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPublicIPsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublicIPsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockPublicIPsServer) Get(arg0 context.Context, arg1 *privatev1.PublicIPsGetRequest) (*privatev1.PublicIPsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublicIPsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublicIPsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockPublicIPsServer) List(arg0 context.Context, arg1 *privatev1.PublicIPsListRequest) (*privatev1.PublicIPsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPublicIPsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPublicIPsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockPublicIPsServer) Signal(arg0 context.Context, arg1 *privatev1.PublicIPsSignalRequest) (*privatev1.PublicIPsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockPublicIPsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockPublicIPsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockPublicIPsServer) Update(arg0 context.Context, arg1 *privatev1.PublicIPsUpdateRequest) (*privatev1.PublicIPsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPublicIPsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublicIPsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedPublicIPsServer mocks base method.
func (m *MockPublicIPsServer) mustEmbedUnimplementedPublicIPsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPublicIPsServer")
}

// mustEmbedUnimplementedPublicIPsServer indicates an expected call of mustEmbedUnimplementedPublicIPsServer.
func (mr *MockPublicIPsServerMockRecorder) mustEmbedUnimplementedPublicIPsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPublicIPsServer", reflect.TypeOf((*MockPublicIPsServer)(nil).mustEmbedUnimplementedPublicIPsServer))
}

// MockUnsafePublicIPsServer is a mock of UnsafePublicIPsServer interface.
type MockUnsafePublicIPsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafePublicIPsServerMockRecorder
	isgomock struct{}
}

// MockUnsafePublicIPsServerMockRecorder is the mock recorder for MockUnsafePublicIPsServer.
type MockUnsafePublicIPsServerMockRecorder struct {
	mock *MockUnsafePublicIPsServer
}

// NewMockUnsafePublicIPsServer creates a new mock instance.
func NewMockUnsafePublicIPsServer(ctrl *gomock.Controller) *MockUnsafePublicIPsServer {
	mock := &MockUnsafePublicIPsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafePublicIPsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafePublicIPsServer) EXPECT() *MockUnsafePublicIPsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedPublicIPsServer mocks base method.
func (m *MockUnsafePublicIPsServer) mustEmbedUnimplementedPublicIPsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPublicIPsServer")
}

// mustEmbedUnimplementedPublicIPsServer indicates an expected call of mustEmbedUnimplementedPublicIPsServer.
func (mr *MockUnsafePublicIPsServerMockRecorder) mustEmbedUnimplementedPublicIPsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPublicIPsServer", reflect.TypeOf((*MockUnsafePublicIPsServer)(nil).mustEmbedUnimplementedPublicIPsServer))
}
