// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/public_ip_pools_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/public_ip_pools_service_grpc.pb.go -destination=public_ip_pools_client_mock.go -package=publicippool PublicIPPoolsClient
//

// Package publicippool is a generated GoMock package.
package publicippool

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPublicIPPoolsClient is a mock of PublicIPPoolsClient interface.
type MockPublicIPPoolsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIPPoolsClientMockRecorder
	isgomock struct{}
}

// MockPublicIPPoolsClientMockRecorder is the mock recorder for MockPublicIPPoolsClient.
type MockPublicIPPoolsClientMockRecorder struct {
	mock *MockPublicIPPoolsClient
}

// NewMockPublicIPPoolsClient creates a new mock instance.
func NewMockPublicIPPoolsClient(ctrl *gomock.Controller) *MockPublicIPPoolsClient {
	mock := &MockPublicIPPoolsClient{ctrl: ctrl}
	mock.recorder = &MockPublicIPPoolsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIPPoolsClient) EXPECT() *MockPublicIPPoolsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublicIPPoolsClient) Create(ctx context.Context, in *privatev1.PublicIPPoolsCreateRequest, opts ...grpc.CallOption) (*privatev1.PublicIPPoolsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPublicIPPoolsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublicIPPoolsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockPublicIPPoolsClient) Delete(ctx context.Context, in *privatev1.PublicIPPoolsDeleteRequest, opts ...grpc.CallOption) (*privatev1.PublicIPPoolsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPublicIPPoolsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublicIPPoolsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockPublicIPPoolsClient) Get(ctx context.Context, in *privatev1.PublicIPPoolsGetRequest, opts ...grpc.CallOption) (*privatev1.PublicIPPoolsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublicIPPoolsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublicIPPoolsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockPublicIPPoolsClient) List(ctx context.Context, in *privatev1.PublicIPPoolsListRequest, opts ...grpc.CallOption) (*privatev1.PublicIPPoolsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPublicIPPoolsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPublicIPPoolsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockPublicIPPoolsClient) Signal(ctx context.Context, in *privatev1.PublicIPPoolsSignalRequest, opts ...grpc.CallOption) (*privatev1.PublicIPPoolsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockPublicIPPoolsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockPublicIPPoolsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockPublicIPPoolsClient) Update(ctx context.Context, in *privatev1.PublicIPPoolsUpdateRequest, opts ...grpc.CallOption) (*privatev1.PublicIPPoolsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPublicIPPoolsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublicIPPoolsClient)(nil).Update), varargs...)
}

// MockPublicIPPoolsServer is a mock of PublicIPPoolsServer interface.
type MockPublicIPPoolsServer struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIPPoolsServerMockRecorder
	isgomock struct{}
}

// MockPublicIPPoolsServerMockRecorder is the mock recorder for MockPublicIPPoolsServer.
type MockPublicIPPoolsServerMockRecorder struct {
	mock *MockPublicIPPoolsServer
}

// NewMockPublicIPPoolsServer creates a new mock instance.
func NewMockPublicIPPoolsServer(ctrl *gomock.Controller) *MockPublicIPPoolsServer {
	mock := &MockPublicIPPoolsServer{ctrl: ctrl}
	mock.recorder = &MockPublicIPPoolsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIPPoolsServer) EXPECT() *MockPublicIPPoolsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublicIPPoolsServer) Create(arg0 context.Context, arg1 *privatev1.PublicIPPoolsCreateRequest) (*privatev1.PublicIPPoolsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPublicIPPoolsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPublicIPPoolsServer) Delete(arg0 context.Context, arg1 *privatev1.PublicIPPoolsDeleteRequest) (*privatev1.PublicIPPoolsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPublicIPPoolsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockPublicIPPoolsServer) Get(arg0 context.Context, arg1 *privatev1.PublicIPPoolsGetRequest) (*privatev1.PublicIPPoolsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublicIPPoolsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockPublicIPPoolsServer) List(arg0 context.Context, arg1 *privatev1.PublicIPPoolsListRequest) (*privatev1.PublicIPPoolsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPublicIPPoolsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockPublicIPPoolsServer) Signal(arg0 context.Context, arg1 *privatev1.PublicIPPoolsSignalRequest) (*privatev1.PublicIPPoolsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockPublicIPPoolsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockPublicIPPoolsServer) Update(arg0 context.Context, arg1 *privatev1.PublicIPPoolsUpdateRequest) (*privatev1.PublicIPPoolsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.PublicIPPoolsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPublicIPPoolsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedPublicIPPoolsServer mocks base method.
func (m *MockPublicIPPoolsServer) mustEmbedUnimplementedPublicIPPoolsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPublicIPPoolsServer")
}

// mustEmbedUnimplementedPublicIPPoolsServer indicates an expected call of mustEmbedUnimplementedPublicIPPoolsServer.
func (mr *MockPublicIPPoolsServerMockRecorder) mustEmbedUnimplementedPublicIPPoolsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPublicIPPoolsServer", reflect.TypeOf((*MockPublicIPPoolsServer)(nil).mustEmbedUnimplementedPublicIPPoolsServer))
}

// MockUnsafePublicIPPoolsServer is a mock of UnsafePublicIPPoolsServer interface.
type MockUnsafePublicIPPoolsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafePublicIPPoolsServerMockRecorder
	isgomock struct{}
}

// MockUnsafePublicIPPoolsServerMockRecorder is the mock recorder for MockUnsafePublicIPPoolsServer.
type MockUnsafePublicIPPoolsServerMockRecorder struct {
	mock *MockUnsafePublicIPPoolsServer
}

// NewMockUnsafePublicIPPoolsServer creates a new mock instance.
func NewMockUnsafePublicIPPoolsServer(ctrl *gomock.Controller) *MockUnsafePublicIPPoolsServer {
	mock := &MockUnsafePublicIPPoolsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafePublicIPPoolsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafePublicIPPoolsServer) EXPECT() *MockUnsafePublicIPPoolsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedPublicIPPoolsServer mocks base method.
func (m *MockUnsafePublicIPPoolsServer) mustEmbedUnimplementedPublicIPPoolsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPublicIPPoolsServer")
}

// mustEmbedUnimplementedPublicIPPoolsServer indicates an expected call of mustEmbedUnimplementedPublicIPPoolsServer.
func (mr *MockUnsafePublicIPPoolsServerMockRecorder) mustEmbedUnimplementedPublicIPPoolsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPublicIPPoolsServer", reflect.TypeOf((*MockUnsafePublicIPPoolsServer)(nil).mustEmbedUnimplementedPublicIPPoolsServer))
}
