#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

name: Setup development tools
runs:
  using: composite
  steps:

  # Go and Ginkgo:
  - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6
    with:
      go-version: '1.26.3'
  - shell: bash
    run: |
      go mod download
  - id: ginkgo-cache
    uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5
    with:
      key: ginkgo-${{ hashFiles('go.mod') }}
      path: ~/go/bin/ginkgo
  - if: steps.ginkgo-cache.outputs.cache-hit != 'true'
    shell: bash
    run: |
      module="github.com/onsi/ginkgo/v2"
      version=$(go list -f '{{ .Version }}' -m "${module}")
      go install "${module}/ginkgo@${version}"

  # Python, uv, and ruff:
  - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
    with:
      python-version: '3.14'
  - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
  - shell: bash
    run: uv tool install ruff==0.15.16

  # Project-specific tools installed by 'dev.py'. The cache key includes the hash of 'dev/tools.py'
  # because that file defines the tool names, versions, and checksums. Any change there means
  # different binaries should be installed.
  - id: dev-cache
    uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5
    with:
      key: dev-${{ runner.os }}-${{ hashFiles('dev/tools.py') }}
      path: bin
  - if: steps.dev-cache.outputs.cache-hit != 'true'
    shell: bash
    run: uv run dev.py setup
  - shell: bash
    run: echo "${GITHUB_WORKSPACE}/bin" >> "${GITHUB_PATH}"
