{{- if .Values.bundledPostgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fulfillment-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fulfillment-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgres://{{ .Values.bundledPostgres.database.user }}@postgres:5432/{{ .Values.bundledPostgres.database.name }}?sslmode=verify-full&sslrootcert=/etc/fulfillment-grpc-server/db/sslrootcert&sslcert=/etc/fulfillment-grpc-server/db/sslcert&sslkey=/etc/fulfillment-grpc-server/db/sslkey"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-client-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fulfillment-service.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ .Values.certs.issuerRef.kind }}
    name: {{ .Values.certs.issuerRef.name }}
  commonName: {{ .Values.bundledPostgres.database.user }}
  usages:
  - client auth
  secretName: postgres-client-cert-service
  privateKey:
    rotationPolicy: Always
{{- end }}
