{{- if .Values.auth.controllerCredentialsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: fulfillment-controller-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fulfillment-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.auth.controllerCredentialsSecret.clientId | quote }}
  client-secret: {{ .Values.auth.controllerCredentialsSecret.clientSecret | quote }}
{{- end }}
