// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/auth (interfaces: AttributionLogic)
//
// Generated by this command:
//
//	mockgen -destination=attribution_logic_mock.go -package=auth . AttributionLogic
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	collections "github.com/osac-project/fulfillment-service/internal/collections"
	gomock "go.uber.org/mock/gomock"
)

// MockAttributionLogic is a mock of AttributionLogic interface.
type MockAttributionLogic struct {
	ctrl     *gomock.Controller
	recorder *MockAttributionLogicMockRecorder
	isgomock struct{}
}

// MockAttributionLogicMockRecorder is the mock recorder for MockAttributionLogic.
type MockAttributionLogicMockRecorder struct {
	mock *MockAttributionLogic
}

// NewMockAttributionLogic creates a new mock instance.
func NewMockAttributionLogic(ctrl *gomock.Controller) *MockAttributionLogic {
	mock := &MockAttributionLogic{ctrl: ctrl}
	mock.recorder = &MockAttributionLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttributionLogic) EXPECT() *MockAttributionLogicMockRecorder {
	return m.recorder
}

// DetermineAssignedCreators mocks base method.
func (m *MockAttributionLogic) DetermineAssignedCreators(ctx context.Context) (collections.Set[string], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetermineAssignedCreators", ctx)
	ret0, _ := ret[0].(collections.Set[string])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetermineAssignedCreators indicates an expected call of DetermineAssignedCreators.
func (mr *MockAttributionLogicMockRecorder) DetermineAssignedCreators(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetermineAssignedCreators", reflect.TypeOf((*MockAttributionLogic)(nil).DetermineAssignedCreators), ctx)
}
