//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/authn_capabilities_type.proto

//go:build !protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents an OAuth token issuer with both an in-cluster and an external URL.
type TokenIssuer struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The in-cluster URL of the OAuth issuer (e.g. the internal Keycloak service URL). Used by
	// services running inside the cluster for server-side token validation.
	InternalUrl string `protobuf:"bytes,1,opt,name=internal_url,json=internalUrl,proto3" json:"internal_url,omitempty"`
	// The externally accessible URL of the OAuth issuer. Clients running outside the cluster
	// (browsers, CLI) should use this URL to perform OAuth flows (authorization code, device flow,
	// etc.). The tokens issued via this URL are accepted by the server because the external and
	// internal Keycloak instances are the same — only the hostname differs.
	ExternalUrl   string `protobuf:"bytes,2,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIssuer) Reset() {
	*x = TokenIssuer{}
	mi := &file_osac_public_v1_authn_capabilities_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIssuer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIssuer) ProtoMessage() {}

func (x *TokenIssuer) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_authn_capabilities_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenIssuer) GetInternalUrl() string {
	if x != nil {
		return x.InternalUrl
	}
	return ""
}

func (x *TokenIssuer) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *TokenIssuer) SetInternalUrl(v string) {
	x.InternalUrl = v
}

func (x *TokenIssuer) SetExternalUrl(v string) {
	x.ExternalUrl = v
}

type TokenIssuer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The in-cluster URL of the OAuth issuer (e.g. the internal Keycloak service URL). Used by
	// services running inside the cluster for server-side token validation.
	InternalUrl string
	// The externally accessible URL of the OAuth issuer. Clients running outside the cluster
	// (browsers, CLI) should use this URL to perform OAuth flows (authorization code, device flow,
	// etc.). The tokens issued via this URL are accepted by the server because the external and
	// internal Keycloak instances are the same — only the hostname differs.
	ExternalUrl string
}

func (b0 TokenIssuer_builder) Build() *TokenIssuer {
	m0 := &TokenIssuer{}
	b, x := &b0, m0
	_, _ = b, x
	x.InternalUrl = b.InternalUrl
	x.ExternalUrl = b.ExternalUrl
	return m0
}

// Contains the information that helps client know how authentication is managed by the server.
type AuthnCapabilities struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// A list of the OAuth token issuers trusted by the server.
	//
	// Each entry exposes both an in-cluster URL (for server-side validation and in-cluster clients)
	// and an external URL (for browsers and external CLI users performing OAuth flows).
	//
	// Clients can use the OAuth discovery endpoint to find the details of the OAuth server:
	//
	//	https://my.oauth.com/.well-known/oauth-authorization-server
	//
	// The discovery process is defined in [RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414).
	//
	// Note that having an access token issued by one of these servers doesn't guarantee that the
	// requests from the user will be accepted: it will still be subject to authorization checks.
	TrustedTokenIssuers []*TokenIssuer `protobuf:"bytes,1,rep,name=trusted_token_issuers,json=trustedTokenIssuers,proto3" json:"trusted_token_issuers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthnCapabilities) Reset() {
	*x = AuthnCapabilities{}
	mi := &file_osac_public_v1_authn_capabilities_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnCapabilities) ProtoMessage() {}

func (x *AuthnCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_authn_capabilities_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthnCapabilities) GetTrustedTokenIssuers() []*TokenIssuer {
	if x != nil {
		return x.TrustedTokenIssuers
	}
	return nil
}

func (x *AuthnCapabilities) SetTrustedTokenIssuers(v []*TokenIssuer) {
	x.TrustedTokenIssuers = v
}

type AuthnCapabilities_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of the OAuth token issuers trusted by the server.
	//
	// Each entry exposes both an in-cluster URL (for server-side validation and in-cluster clients)
	// and an external URL (for browsers and external CLI users performing OAuth flows).
	//
	// Clients can use the OAuth discovery endpoint to find the details of the OAuth server:
	//
	//	https://my.oauth.com/.well-known/oauth-authorization-server
	//
	// The discovery process is defined in [RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414).
	//
	// Note that having an access token issued by one of these servers doesn't guarantee that the
	// requests from the user will be accepted: it will still be subject to authorization checks.
	TrustedTokenIssuers []*TokenIssuer
}

func (b0 AuthnCapabilities_builder) Build() *AuthnCapabilities {
	m0 := &AuthnCapabilities{}
	b, x := &b0, m0
	_, _ = b, x
	x.TrustedTokenIssuers = b.TrustedTokenIssuers
	return m0
}

var File_osac_public_v1_authn_capabilities_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_authn_capabilities_type_proto_rawDesc = string([]byte{
	0x0a, 0x2c, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x53,
	0x0a, 0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x55, 0x72, 0x6c, 0x22, 0x64, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x43, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x15, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x52, 0x13, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x73, 0x42, 0xde, 0x01, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x42, 0x1a, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var file_osac_public_v1_authn_capabilities_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_osac_public_v1_authn_capabilities_type_proto_goTypes = []any{
	(*TokenIssuer)(nil),       // 0: osac.public.v1.TokenIssuer
	(*AuthnCapabilities)(nil), // 1: osac.public.v1.AuthnCapabilities
}
var file_osac_public_v1_authn_capabilities_type_proto_depIdxs = []int32{
	0, // 0: osac.public.v1.AuthnCapabilities.trusted_token_issuers:type_name -> osac.public.v1.TokenIssuer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_osac_public_v1_authn_capabilities_type_proto_init() }
func file_osac_public_v1_authn_capabilities_type_proto_init() {
	if File_osac_public_v1_authn_capabilities_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_authn_capabilities_type_proto_rawDesc), len(file_osac_public_v1_authn_capabilities_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_authn_capabilities_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_authn_capabilities_type_proto_depIdxs,
		MessageInfos:      file_osac_public_v1_authn_capabilities_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_authn_capabilities_type_proto = out.File
	file_osac_public_v1_authn_capabilities_type_proto_goTypes = nil
	file_osac_public_v1_authn_capabilities_type_proto_depIdxs = nil
}
