//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/public/v1/hosts_service.proto

package publicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hosts_List_FullMethodName   = "/osac.public.v1.Hosts/List"
	Hosts_Get_FullMethodName    = "/osac.public.v1.Hosts/Get"
	Hosts_Create_FullMethodName = "/osac.public.v1.Hosts/Create"
	Hosts_Update_FullMethodName = "/osac.public.v1.Hosts/Update"
	Hosts_Delete_FullMethodName = "/osac.public.v1.Hosts/Delete"
)

// HostsClient is the client API for Hosts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostsClient interface {
	// Retrieves the list of hosts.
	List(ctx context.Context, in *HostsListRequest, opts ...grpc.CallOption) (*HostsListResponse, error)
	// Retrieves the details of one specific host.
	Get(ctx context.Context, in *HostsGetRequest, opts ...grpc.CallOption) (*HostsGetResponse, error)
	// Creates a new host.
	Create(ctx context.Context, in *HostsCreateRequest, opts ...grpc.CallOption) (*HostsCreateResponse, error)
	// Updates an existing host.
	//
	// In the HTTP+JSON version of the API this is mapped to the `PATCH` verb and the `update_mask` field is automatically
	// populated from the list of fields present in the request body. For example, to update the `title` of a host to
	// `foo` the request line should be like this:
	//
	// ```http
	// PATCH /api/fulfillment/v1/hosts/123
	// ```
	//
	// And the request body should be like this:
	//
	// ```json
	//
	//	{
	//	  "title": "foo"
	//	}
	//
	// ```
	//
	// The response body will contain the modified object.
	Update(ctx context.Context, in *HostsUpdateRequest, opts ...grpc.CallOption) (*HostsUpdateResponse, error)
	// Delete a host.
	Delete(ctx context.Context, in *HostsDeleteRequest, opts ...grpc.CallOption) (*HostsDeleteResponse, error)
}

type hostsClient struct {
	cc grpc.ClientConnInterface
}

func NewHostsClient(cc grpc.ClientConnInterface) HostsClient {
	return &hostsClient{cc}
}

func (c *hostsClient) List(ctx context.Context, in *HostsListRequest, opts ...grpc.CallOption) (*HostsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostsListResponse)
	err := c.cc.Invoke(ctx, Hosts_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Get(ctx context.Context, in *HostsGetRequest, opts ...grpc.CallOption) (*HostsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostsGetResponse)
	err := c.cc.Invoke(ctx, Hosts_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Create(ctx context.Context, in *HostsCreateRequest, opts ...grpc.CallOption) (*HostsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostsCreateResponse)
	err := c.cc.Invoke(ctx, Hosts_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Update(ctx context.Context, in *HostsUpdateRequest, opts ...grpc.CallOption) (*HostsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostsUpdateResponse)
	err := c.cc.Invoke(ctx, Hosts_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Delete(ctx context.Context, in *HostsDeleteRequest, opts ...grpc.CallOption) (*HostsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostsDeleteResponse)
	err := c.cc.Invoke(ctx, Hosts_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostsServer is the server API for Hosts service.
// All implementations must embed UnimplementedHostsServer
// for forward compatibility.
type HostsServer interface {
	// Retrieves the list of hosts.
	List(context.Context, *HostsListRequest) (*HostsListResponse, error)
	// Retrieves the details of one specific host.
	Get(context.Context, *HostsGetRequest) (*HostsGetResponse, error)
	// Creates a new host.
	Create(context.Context, *HostsCreateRequest) (*HostsCreateResponse, error)
	// Updates an existing host.
	//
	// In the HTTP+JSON version of the API this is mapped to the `PATCH` verb and the `update_mask` field is automatically
	// populated from the list of fields present in the request body. For example, to update the `title` of a host to
	// `foo` the request line should be like this:
	//
	// ```http
	// PATCH /api/fulfillment/v1/hosts/123
	// ```
	//
	// And the request body should be like this:
	//
	// ```json
	//
	//	{
	//	  "title": "foo"
	//	}
	//
	// ```
	//
	// The response body will contain the modified object.
	Update(context.Context, *HostsUpdateRequest) (*HostsUpdateResponse, error)
	// Delete a host.
	Delete(context.Context, *HostsDeleteRequest) (*HostsDeleteResponse, error)
	mustEmbedUnimplementedHostsServer()
}

// UnimplementedHostsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostsServer struct{}

func (UnimplementedHostsServer) List(context.Context, *HostsListRequest) (*HostsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedHostsServer) Get(context.Context, *HostsGetRequest) (*HostsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHostsServer) Create(context.Context, *HostsCreateRequest) (*HostsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedHostsServer) Update(context.Context, *HostsUpdateRequest) (*HostsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedHostsServer) Delete(context.Context, *HostsDeleteRequest) (*HostsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedHostsServer) mustEmbedUnimplementedHostsServer() {}
func (UnimplementedHostsServer) testEmbeddedByValue()               {}

// UnsafeHostsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostsServer will
// result in compilation errors.
type UnsafeHostsServer interface {
	mustEmbedUnimplementedHostsServer()
}

func RegisterHostsServer(s grpc.ServiceRegistrar, srv HostsServer) {
	// If the following call pancis, it indicates UnimplementedHostsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hosts_ServiceDesc, srv)
}

func _Hosts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).List(ctx, req.(*HostsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Get(ctx, req.(*HostsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Create(ctx, req.(*HostsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Update(ctx, req.(*HostsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Delete(ctx, req.(*HostsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hosts_ServiceDesc is the grpc.ServiceDesc for Hosts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hosts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.public.v1.Hosts",
	HandlerType: (*HostsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Hosts_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Hosts_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Hosts_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Hosts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Hosts_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/public/v1/hosts_service.proto",
}
