//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/public_ip_pool_type.proto

//go:build !protoopaque

package publicv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IP address family for a PublicIPPool.
type IPFamily int32

const (
	// IP family is unknown or has not been specified.
	IPFamily_IP_FAMILY_UNSPECIFIED IPFamily = 0
	// IPv4 address family.
	IPFamily_IP_FAMILY_IPV4 IPFamily = 1
	// IPv6 address family.
	IPFamily_IP_FAMILY_IPV6 IPFamily = 2
)

// Enum value maps for IPFamily.
var (
	IPFamily_name = map[int32]string{
		0: "IP_FAMILY_UNSPECIFIED",
		1: "IP_FAMILY_IPV4",
		2: "IP_FAMILY_IPV6",
	}
	IPFamily_value = map[string]int32{
		"IP_FAMILY_UNSPECIFIED": 0,
		"IP_FAMILY_IPV4":        1,
		"IP_FAMILY_IPV6":        2,
	}
)

func (x IPFamily) Enum() *IPFamily {
	p := new(IPFamily)
	*p = x
	return p
}

func (x IPFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_public_ip_pool_type_proto_enumTypes[0].Descriptor()
}

func (IPFamily) Type() protoreflect.EnumType {
	return &file_osac_public_v1_public_ip_pool_type_proto_enumTypes[0]
}

func (x IPFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a pool of public IP addresses available for allocation.
//
// PublicIPPools are administrator-managed resources. The public API only surfaces pools that are
// ready and have available capacity.
// Tenants use this resource to discover available pools and select one when allocating a PublicIP.
type PublicIPPool struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the public IP pool.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the public IP pool, including name, labels, and timestamps.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Configuration of the public IP pool.
	Spec *PublicIPPoolSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current capacity information for this pool (system-provided, read-only).
	Status        *PublicIPPoolStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPPool) Reset() {
	*x = PublicIPPool{}
	mi := &file_osac_public_v1_public_ip_pool_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPPool) ProtoMessage() {}

func (x *PublicIPPool) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_public_ip_pool_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPPool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicIPPool) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublicIPPool) GetSpec() *PublicIPPoolSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PublicIPPool) GetStatus() *PublicIPPoolStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PublicIPPool) SetId(v string) {
	x.Id = v
}

func (x *PublicIPPool) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *PublicIPPool) SetSpec(v *PublicIPPoolSpec) {
	x.Spec = v
}

func (x *PublicIPPool) SetStatus(v *PublicIPPoolStatus) {
	x.Status = v
}

func (x *PublicIPPool) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *PublicIPPool) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *PublicIPPool) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *PublicIPPool) ClearMetadata() {
	x.Metadata = nil
}

func (x *PublicIPPool) ClearSpec() {
	x.Spec = nil
}

func (x *PublicIPPool) ClearStatus() {
	x.Status = nil
}

type PublicIPPool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the public IP pool.
	Id string
	// Metadata of the public IP pool, including name, labels, and timestamps.
	Metadata *Metadata
	// Configuration of the public IP pool.
	Spec *PublicIPPoolSpec
	// Current capacity information for this pool (system-provided, read-only).
	Status *PublicIPPoolStatus
}

func (b0 PublicIPPool_builder) Build() *PublicIPPool {
	m0 := &PublicIPPool{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the configuration of a PublicIPPool.
type PublicIPPoolSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// IP address family for this pool. Immutable after creation.
	IpFamily      IPFamily `protobuf:"varint,3,opt,name=ip_family,json=ipFamily,proto3,enum=osac.public.v1.IPFamily" json:"ip_family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPPoolSpec) Reset() {
	*x = PublicIPPoolSpec{}
	mi := &file_osac_public_v1_public_ip_pool_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPPoolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPPoolSpec) ProtoMessage() {}

func (x *PublicIPPoolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_public_ip_pool_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPPoolSpec) GetIpFamily() IPFamily {
	if x != nil {
		return x.IpFamily
	}
	return IPFamily_IP_FAMILY_UNSPECIFIED
}

func (x *PublicIPPoolSpec) SetIpFamily(v IPFamily) {
	x.IpFamily = v
}

type PublicIPPoolSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// IP address family for this pool. Immutable after creation.
	IpFamily IPFamily
}

func (b0 PublicIPPoolSpec_builder) Build() *PublicIPPoolSpec {
	m0 := &PublicIPPoolSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.IpFamily = b.IpFamily
	return m0
}

// Capacity information for a PublicIPPool exposed to tenants.
type PublicIPPoolStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Number of IP addresses available for new allocations from this pool.
	Available     int64 `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPPoolStatus) Reset() {
	*x = PublicIPPoolStatus{}
	mi := &file_osac_public_v1_public_ip_pool_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPPoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPPoolStatus) ProtoMessage() {}

func (x *PublicIPPoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_public_ip_pool_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPPoolStatus) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *PublicIPPoolStatus) SetAvailable(v int64) {
	x.Available = v
}

type PublicIPPoolStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of IP addresses available for new allocations from this pool.
	Available int64
}

func (b0 PublicIPPoolStatus_builder) Build() *PublicIPPoolStatus {
	m0 := &PublicIPPoolStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.Available = b.Available
	return m0
}

var File_osac_public_v1_public_ip_pool_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_public_ip_pool_type_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc6, 0x01, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f,
	0x6f, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3a, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x54, 0x0a, 0x10, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x12, 0x3a, 0x0a, 0x09,
	0x69, 0x70, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x50, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x42, 0x03, 0xe0, 0x41, 0x05, 0x52, 0x08,
	0x69, 0x70, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x37,
	0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2a, 0x4d, 0x0a, 0x08, 0x49, 0x50, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x50, 0x5f, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x49, 0x50, 0x5f, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f, 0x49, 0x50, 0x56, 0x34,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x50, 0x5f, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f,
	0x49, 0x50, 0x56, 0x36, 0x10, 0x02, 0x42, 0xd9, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x70, 0x50, 0x6f, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f,
	0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02,
	0x0e, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x1b, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_public_ip_pool_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_public_v1_public_ip_pool_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_public_v1_public_ip_pool_type_proto_goTypes = []any{
	(IPFamily)(0),              // 0: osac.public.v1.IPFamily
	(*PublicIPPool)(nil),       // 1: osac.public.v1.PublicIPPool
	(*PublicIPPoolSpec)(nil),   // 2: osac.public.v1.PublicIPPoolSpec
	(*PublicIPPoolStatus)(nil), // 3: osac.public.v1.PublicIPPoolStatus
	(*Metadata)(nil),           // 4: osac.public.v1.Metadata
}
var file_osac_public_v1_public_ip_pool_type_proto_depIdxs = []int32{
	4, // 0: osac.public.v1.PublicIPPool.metadata:type_name -> osac.public.v1.Metadata
	2, // 1: osac.public.v1.PublicIPPool.spec:type_name -> osac.public.v1.PublicIPPoolSpec
	3, // 2: osac.public.v1.PublicIPPool.status:type_name -> osac.public.v1.PublicIPPoolStatus
	0, // 3: osac.public.v1.PublicIPPoolSpec.ip_family:type_name -> osac.public.v1.IPFamily
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_public_v1_public_ip_pool_type_proto_init() }
func file_osac_public_v1_public_ip_pool_type_proto_init() {
	if File_osac_public_v1_public_ip_pool_type_proto != nil {
		return
	}
	file_osac_public_v1_metadata_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_public_ip_pool_type_proto_rawDesc), len(file_osac_public_v1_public_ip_pool_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_public_ip_pool_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_public_ip_pool_type_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_public_ip_pool_type_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_public_ip_pool_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_public_ip_pool_type_proto = out.File
	file_osac_public_v1_public_ip_pool_type_proto_goTypes = nil
	file_osac_public_v1_public_ip_pool_type_proto_depIdxs = nil
}
