//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/reference_types.proto

//go:build !protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Local reference to a VirtualNetwork resource.
type VirtualNetworkLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualNetworkLocalReference) Reset() {
	*x = VirtualNetworkLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualNetworkLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualNetworkLocalReference) ProtoMessage() {}

func (x *VirtualNetworkLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VirtualNetworkLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VirtualNetworkLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualNetworkLocalReference) SetId(v string) {
	x.Id = v
}

func (x *VirtualNetworkLocalReference) SetName(v string) {
	x.Name = v
}

type VirtualNetworkLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 VirtualNetworkLocalReference_builder) Build() *VirtualNetworkLocalReference {
	m0 := &VirtualNetworkLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Reference to a NetworkClass resource.
type NetworkClassReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClassReference) Reset() {
	*x = NetworkClassReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassReference) ProtoMessage() {}

func (x *NetworkClassReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkClassReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkClassReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkClassReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *NetworkClassReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *NetworkClassReference) SetId(v string) {
	x.Id = v
}

func (x *NetworkClassReference) SetName(v string) {
	x.Name = v
}

func (x *NetworkClassReference) SetProject(v string) {
	x.Project = v
}

func (x *NetworkClassReference) SetShared(v bool) {
	x.Shared = v
}

type NetworkClassReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 NetworkClassReference_builder) Build() *NetworkClassReference {
	m0 := &NetworkClassReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Local reference to a Subnet resource.
type SubnetLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetLocalReference) Reset() {
	*x = SubnetLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetLocalReference) ProtoMessage() {}

func (x *SubnetLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubnetLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubnetLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubnetLocalReference) SetId(v string) {
	x.Id = v
}

func (x *SubnetLocalReference) SetName(v string) {
	x.Name = v
}

type SubnetLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 SubnetLocalReference_builder) Build() *SubnetLocalReference {
	m0 := &SubnetLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Local reference to a SecurityGroup resource.
type SecurityGroupLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityGroupLocalReference) Reset() {
	*x = SecurityGroupLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityGroupLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityGroupLocalReference) ProtoMessage() {}

func (x *SecurityGroupLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityGroupLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityGroupLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityGroupLocalReference) SetId(v string) {
	x.Id = v
}

func (x *SecurityGroupLocalReference) SetName(v string) {
	x.Name = v
}

type SecurityGroupLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 SecurityGroupLocalReference_builder) Build() *SecurityGroupLocalReference {
	m0 := &SecurityGroupLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Local reference to an ExternalIP resource.
type ExternalIPLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalIPLocalReference) Reset() {
	*x = ExternalIPLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalIPLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalIPLocalReference) ProtoMessage() {}

func (x *ExternalIPLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExternalIPLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalIPLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalIPLocalReference) SetId(v string) {
	x.Id = v
}

func (x *ExternalIPLocalReference) SetName(v string) {
	x.Name = v
}

type ExternalIPLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 ExternalIPLocalReference_builder) Build() *ExternalIPLocalReference {
	m0 := &ExternalIPLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Reference to an ExternalIPPool resource.
type ExternalIPPoolReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalIPPoolReference) Reset() {
	*x = ExternalIPPoolReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalIPPoolReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalIPPoolReference) ProtoMessage() {}

func (x *ExternalIPPoolReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExternalIPPoolReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalIPPoolReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalIPPoolReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ExternalIPPoolReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *ExternalIPPoolReference) SetId(v string) {
	x.Id = v
}

func (x *ExternalIPPoolReference) SetName(v string) {
	x.Name = v
}

func (x *ExternalIPPoolReference) SetProject(v string) {
	x.Project = v
}

func (x *ExternalIPPoolReference) SetShared(v bool) {
	x.Shared = v
}

type ExternalIPPoolReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 ExternalIPPoolReference_builder) Build() *ExternalIPPoolReference {
	m0 := &ExternalIPPoolReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Local reference to a ComputeInstance resource.
type ComputeInstanceLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceLocalReference) Reset() {
	*x = ComputeInstanceLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceLocalReference) ProtoMessage() {}

func (x *ComputeInstanceLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeInstanceLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComputeInstanceLocalReference) SetId(v string) {
	x.Id = v
}

func (x *ComputeInstanceLocalReference) SetName(v string) {
	x.Name = v
}

type ComputeInstanceLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 ComputeInstanceLocalReference_builder) Build() *ComputeInstanceLocalReference {
	m0 := &ComputeInstanceLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Reference to a ComputeInstanceTemplate resource.
type ComputeInstanceTemplateReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceTemplateReference) Reset() {
	*x = ComputeInstanceTemplateReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceTemplateReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceTemplateReference) ProtoMessage() {}

func (x *ComputeInstanceTemplateReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceTemplateReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeInstanceTemplateReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComputeInstanceTemplateReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ComputeInstanceTemplateReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *ComputeInstanceTemplateReference) SetId(v string) {
	x.Id = v
}

func (x *ComputeInstanceTemplateReference) SetName(v string) {
	x.Name = v
}

func (x *ComputeInstanceTemplateReference) SetProject(v string) {
	x.Project = v
}

func (x *ComputeInstanceTemplateReference) SetShared(v bool) {
	x.Shared = v
}

type ComputeInstanceTemplateReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 ComputeInstanceTemplateReference_builder) Build() *ComputeInstanceTemplateReference {
	m0 := &ComputeInstanceTemplateReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to a ComputeInstanceCatalogItem resource.
type ComputeInstanceCatalogItemReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceCatalogItemReference) Reset() {
	*x = ComputeInstanceCatalogItemReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceCatalogItemReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceCatalogItemReference) ProtoMessage() {}

func (x *ComputeInstanceCatalogItemReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceCatalogItemReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeInstanceCatalogItemReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComputeInstanceCatalogItemReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ComputeInstanceCatalogItemReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *ComputeInstanceCatalogItemReference) SetId(v string) {
	x.Id = v
}

func (x *ComputeInstanceCatalogItemReference) SetName(v string) {
	x.Name = v
}

func (x *ComputeInstanceCatalogItemReference) SetProject(v string) {
	x.Project = v
}

func (x *ComputeInstanceCatalogItemReference) SetShared(v bool) {
	x.Shared = v
}

type ComputeInstanceCatalogItemReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 ComputeInstanceCatalogItemReference_builder) Build() *ComputeInstanceCatalogItemReference {
	m0 := &ComputeInstanceCatalogItemReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to an InstanceType resource.
type InstanceTypeReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceTypeReference) Reset() {
	*x = InstanceTypeReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceTypeReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceTypeReference) ProtoMessage() {}

func (x *InstanceTypeReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceTypeReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceTypeReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceTypeReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *InstanceTypeReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *InstanceTypeReference) SetId(v string) {
	x.Id = v
}

func (x *InstanceTypeReference) SetName(v string) {
	x.Name = v
}

func (x *InstanceTypeReference) SetProject(v string) {
	x.Project = v
}

func (x *InstanceTypeReference) SetShared(v bool) {
	x.Shared = v
}

type InstanceTypeReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 InstanceTypeReference_builder) Build() *InstanceTypeReference {
	m0 := &InstanceTypeReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Local reference to an InstanceType resource.
type InstanceTypeLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceTypeLocalReference) Reset() {
	*x = InstanceTypeLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceTypeLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceTypeLocalReference) ProtoMessage() {}

func (x *InstanceTypeLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceTypeLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceTypeLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceTypeLocalReference) SetId(v string) {
	x.Id = v
}

func (x *InstanceTypeLocalReference) SetName(v string) {
	x.Name = v
}

type InstanceTypeLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 InstanceTypeLocalReference_builder) Build() *InstanceTypeLocalReference {
	m0 := &InstanceTypeLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Local reference to a Cluster resource.
type ClusterLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterLocalReference) Reset() {
	*x = ClusterLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterLocalReference) ProtoMessage() {}

func (x *ClusterLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterLocalReference) SetId(v string) {
	x.Id = v
}

func (x *ClusterLocalReference) SetName(v string) {
	x.Name = v
}

type ClusterLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 ClusterLocalReference_builder) Build() *ClusterLocalReference {
	m0 := &ClusterLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Reference to a ClusterTemplate resource.
type ClusterTemplateReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterTemplateReference) Reset() {
	*x = ClusterTemplateReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterTemplateReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTemplateReference) ProtoMessage() {}

func (x *ClusterTemplateReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterTemplateReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterTemplateReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterTemplateReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ClusterTemplateReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *ClusterTemplateReference) SetId(v string) {
	x.Id = v
}

func (x *ClusterTemplateReference) SetName(v string) {
	x.Name = v
}

func (x *ClusterTemplateReference) SetProject(v string) {
	x.Project = v
}

func (x *ClusterTemplateReference) SetShared(v bool) {
	x.Shared = v
}

type ClusterTemplateReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 ClusterTemplateReference_builder) Build() *ClusterTemplateReference {
	m0 := &ClusterTemplateReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to a ClusterCatalogItem resource.
type ClusterCatalogItemReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCatalogItemReference) Reset() {
	*x = ClusterCatalogItemReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCatalogItemReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCatalogItemReference) ProtoMessage() {}

func (x *ClusterCatalogItemReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterCatalogItemReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterCatalogItemReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterCatalogItemReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ClusterCatalogItemReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *ClusterCatalogItemReference) SetId(v string) {
	x.Id = v
}

func (x *ClusterCatalogItemReference) SetName(v string) {
	x.Name = v
}

func (x *ClusterCatalogItemReference) SetProject(v string) {
	x.Project = v
}

func (x *ClusterCatalogItemReference) SetShared(v bool) {
	x.Shared = v
}

type ClusterCatalogItemReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 ClusterCatalogItemReference_builder) Build() *ClusterCatalogItemReference {
	m0 := &ClusterCatalogItemReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to a HostType resource.
type HostTypeReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostTypeReference) Reset() {
	*x = HostTypeReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTypeReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTypeReference) ProtoMessage() {}

func (x *HostTypeReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostTypeReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostTypeReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostTypeReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *HostTypeReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *HostTypeReference) SetId(v string) {
	x.Id = v
}

func (x *HostTypeReference) SetName(v string) {
	x.Name = v
}

func (x *HostTypeReference) SetProject(v string) {
	x.Project = v
}

func (x *HostTypeReference) SetShared(v bool) {
	x.Shared = v
}

type HostTypeReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 HostTypeReference_builder) Build() *HostTypeReference {
	m0 := &HostTypeReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Local reference to a BareMetalInstance resource.
type BareMetalInstanceLocalReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareMetalInstanceLocalReference) Reset() {
	*x = BareMetalInstanceLocalReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareMetalInstanceLocalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareMetalInstanceLocalReference) ProtoMessage() {}

func (x *BareMetalInstanceLocalReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BareMetalInstanceLocalReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BareMetalInstanceLocalReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BareMetalInstanceLocalReference) SetId(v string) {
	x.Id = v
}

func (x *BareMetalInstanceLocalReference) SetName(v string) {
	x.Name = v
}

type BareMetalInstanceLocalReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Name string
}

func (b0 BareMetalInstanceLocalReference_builder) Build() *BareMetalInstanceLocalReference {
	m0 := &BareMetalInstanceLocalReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	return m0
}

// Reference to a BareMetalInstanceCatalogItem resource.
type BareMetalInstanceCatalogItemReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareMetalInstanceCatalogItemReference) Reset() {
	*x = BareMetalInstanceCatalogItemReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareMetalInstanceCatalogItemReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareMetalInstanceCatalogItemReference) ProtoMessage() {}

func (x *BareMetalInstanceCatalogItemReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BareMetalInstanceCatalogItemReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BareMetalInstanceCatalogItemReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BareMetalInstanceCatalogItemReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *BareMetalInstanceCatalogItemReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *BareMetalInstanceCatalogItemReference) SetId(v string) {
	x.Id = v
}

func (x *BareMetalInstanceCatalogItemReference) SetName(v string) {
	x.Name = v
}

func (x *BareMetalInstanceCatalogItemReference) SetProject(v string) {
	x.Project = v
}

func (x *BareMetalInstanceCatalogItemReference) SetShared(v bool) {
	x.Shared = v
}

type BareMetalInstanceCatalogItemReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 BareMetalInstanceCatalogItemReference_builder) Build() *BareMetalInstanceCatalogItemReference {
	m0 := &BareMetalInstanceCatalogItemReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to a BareMetalInstanceTemplate resource.
type BareMetalInstanceTemplateReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareMetalInstanceTemplateReference) Reset() {
	*x = BareMetalInstanceTemplateReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareMetalInstanceTemplateReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareMetalInstanceTemplateReference) ProtoMessage() {}

func (x *BareMetalInstanceTemplateReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BareMetalInstanceTemplateReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BareMetalInstanceTemplateReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BareMetalInstanceTemplateReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *BareMetalInstanceTemplateReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *BareMetalInstanceTemplateReference) SetId(v string) {
	x.Id = v
}

func (x *BareMetalInstanceTemplateReference) SetName(v string) {
	x.Name = v
}

func (x *BareMetalInstanceTemplateReference) SetProject(v string) {
	x.Project = v
}

func (x *BareMetalInstanceTemplateReference) SetShared(v bool) {
	x.Shared = v
}

type BareMetalInstanceTemplateReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 BareMetalInstanceTemplateReference_builder) Build() *BareMetalInstanceTemplateReference {
	m0 := &BareMetalInstanceTemplateReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to a Role resource.
type RoleReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleReference) Reset() {
	*x = RoleReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleReference) ProtoMessage() {}

func (x *RoleReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoleReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RoleReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *RoleReference) SetId(v string) {
	x.Id = v
}

func (x *RoleReference) SetName(v string) {
	x.Name = v
}

func (x *RoleReference) SetProject(v string) {
	x.Project = v
}

func (x *RoleReference) SetShared(v bool) {
	x.Shared = v
}

type RoleReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 RoleReference_builder) Build() *RoleReference {
	m0 := &RoleReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

// Reference to a User resource.
type UserReference struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReference) Reset() {
	*x = UserReference{}
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReference) ProtoMessage() {}

func (x *UserReference) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_reference_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *UserReference) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *UserReference) SetId(v string) {
	x.Id = v
}

func (x *UserReference) SetName(v string) {
	x.Name = v
}

func (x *UserReference) SetProject(v string) {
	x.Project = v
}

func (x *UserReference) SetShared(v bool) {
	x.Shared = v
}

type UserReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      string
	Name    string
	Project string
	Shared  bool
}

func (b0 UserReference_builder) Build() *UserReference {
	m0 := &UserReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Project = b.Project
	x.Shared = b.Shared
	return m0
}

var File_osac_public_v1_reference_types_proto protoreflect.FileDescriptor

var file_osac_public_v1_reference_types_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x42, 0x0a, 0x1c, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6d, 0x0a, 0x15, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x53, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x1b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x18, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x50, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x17, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x43, 0x0a, 0x1d, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x78,
	0x0a, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x7b, 0x0a, 0x23, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x22, 0x40, 0x0a, 0x1a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x15, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x70, 0x0a, 0x18, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x73, 0x0a, 0x1b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x69, 0x0a, 0x11, 0x48, 0x6f,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x45, 0x0a, 0x1f, 0x42, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x25,
	0x42, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x7a, 0x0a, 0x22, 0x42,
	0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x65, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x65,
	0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x42, 0xd7, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x13, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c,
	0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73,
	0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73,
	0x61, 0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f,
	0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x1b, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f,
	0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_reference_types_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_osac_public_v1_reference_types_proto_goTypes = []any{
	(*VirtualNetworkLocalReference)(nil),          // 0: osac.public.v1.VirtualNetworkLocalReference
	(*NetworkClassReference)(nil),                 // 1: osac.public.v1.NetworkClassReference
	(*SubnetLocalReference)(nil),                  // 2: osac.public.v1.SubnetLocalReference
	(*SecurityGroupLocalReference)(nil),           // 3: osac.public.v1.SecurityGroupLocalReference
	(*ExternalIPLocalReference)(nil),              // 4: osac.public.v1.ExternalIPLocalReference
	(*ExternalIPPoolReference)(nil),               // 5: osac.public.v1.ExternalIPPoolReference
	(*ComputeInstanceLocalReference)(nil),         // 6: osac.public.v1.ComputeInstanceLocalReference
	(*ComputeInstanceTemplateReference)(nil),      // 7: osac.public.v1.ComputeInstanceTemplateReference
	(*ComputeInstanceCatalogItemReference)(nil),   // 8: osac.public.v1.ComputeInstanceCatalogItemReference
	(*InstanceTypeReference)(nil),                 // 9: osac.public.v1.InstanceTypeReference
	(*InstanceTypeLocalReference)(nil),            // 10: osac.public.v1.InstanceTypeLocalReference
	(*ClusterLocalReference)(nil),                 // 11: osac.public.v1.ClusterLocalReference
	(*ClusterTemplateReference)(nil),              // 12: osac.public.v1.ClusterTemplateReference
	(*ClusterCatalogItemReference)(nil),           // 13: osac.public.v1.ClusterCatalogItemReference
	(*HostTypeReference)(nil),                     // 14: osac.public.v1.HostTypeReference
	(*BareMetalInstanceLocalReference)(nil),       // 15: osac.public.v1.BareMetalInstanceLocalReference
	(*BareMetalInstanceCatalogItemReference)(nil), // 16: osac.public.v1.BareMetalInstanceCatalogItemReference
	(*BareMetalInstanceTemplateReference)(nil),    // 17: osac.public.v1.BareMetalInstanceTemplateReference
	(*RoleReference)(nil),                         // 18: osac.public.v1.RoleReference
	(*UserReference)(nil),                         // 19: osac.public.v1.UserReference
}
var file_osac_public_v1_reference_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_osac_public_v1_reference_types_proto_init() }
func file_osac_public_v1_reference_types_proto_init() {
	if File_osac_public_v1_reference_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_reference_types_proto_rawDesc), len(file_osac_public_v1_reference_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_reference_types_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_reference_types_proto_depIdxs,
		MessageInfos:      file_osac_public_v1_reference_types_proto_msgTypes,
	}.Build()
	File_osac_public_v1_reference_types_proto = out.File
	file_osac_public_v1_reference_types_proto_goTypes = nil
	file_osac_public_v1_reference_types_proto_depIdxs = nil
}
