//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/public/v1/signing_keys_service.proto

package publicv1

import (
	context "context"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SigningKeys_Get_FullMethodName = "/osac.public.v1.SigningKeys/Get"
)

// SigningKeysClient is the client API for SigningKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides the JSON Web Key Set containing the public signing keys used to verify tokens issued by this server.
// This endpoint does not require authentication.
type SigningKeysClient interface {
	// Returns the JSON Web Key Set (JWKS) containing the public signing keys.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Get(ctx context.Context, in *SigningKeysGetRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
}

type signingKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewSigningKeysClient(cc grpc.ClientConnInterface) SigningKeysClient {
	return &signingKeysClient{cc}
}

func (c *signingKeysClient) Get(ctx context.Context, in *SigningKeysGetRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, SigningKeys_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigningKeysServer is the server API for SigningKeys service.
// All implementations must embed UnimplementedSigningKeysServer
// for forward compatibility.
//
// Provides the JSON Web Key Set containing the public signing keys used to verify tokens issued by this server.
// This endpoint does not require authentication.
type SigningKeysServer interface {
	// Returns the JSON Web Key Set (JWKS) containing the public signing keys.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Get(context.Context, *SigningKeysGetRequest) (*httpbody.HttpBody, error)
	mustEmbedUnimplementedSigningKeysServer()
}

// UnimplementedSigningKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSigningKeysServer struct{}

func (UnimplementedSigningKeysServer) Get(context.Context, *SigningKeysGetRequest) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSigningKeysServer) mustEmbedUnimplementedSigningKeysServer() {}
func (UnimplementedSigningKeysServer) testEmbeddedByValue()                     {}

// UnsafeSigningKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigningKeysServer will
// result in compilation errors.
type UnsafeSigningKeysServer interface {
	mustEmbedUnimplementedSigningKeysServer()
}

func RegisterSigningKeysServer(s grpc.ServiceRegistrar, srv SigningKeysServer) {
	// If the following call pancis, it indicates UnimplementedSigningKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SigningKeys_ServiceDesc, srv)
}

func _SigningKeys_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigningKeysGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningKeysServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningKeys_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningKeysServer).Get(ctx, req.(*SigningKeysGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SigningKeys_ServiceDesc is the grpc.ServiceDesc for SigningKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigningKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.public.v1.SigningKeys",
	HandlerType: (*SigningKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SigningKeys_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/public/v1/signing_keys_service.proto",
}
