{{/*
Copyright (c) 2026 Red Hat Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific
language governing permissions and limitations under the License.
*/}}

{{- $umaCredentials := required "idp.umaCredentials is required" .Values.idp.umaCredentials }}
{{- $clientID := "" }}
{{- $clientSecret := "" }}
{{- range $umaCredentials }}
  {{- if .secret }}
    {{- $secretName := .secret.name }}
    {{- $secret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
    {{- if $secret }}
      {{- range .secret.items }}
        {{- if eq .param "client-id" }}
          {{- $clientID = index $secret.data .key | b64dec }}
        {{- else if eq .param "client-secret" }}
          {{- $clientSecret = index $secret.data .key | b64dec }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if or $clientID $clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-keycloak-uma-credentials
type: Opaque
stringData:
  clientID: "{{ required "UMA client-id not found in idp.umaCredentials" $clientID }}"
  clientSecret: "{{ required "UMA client-secret not found in idp.umaCredentials" $clientSecret }}"
{{- end }}
